module.exports = {
  content: [
    "./pages/index.tsx",
    "./pages/_app.tsx",
    "./pages/components/Header.tsx",
    "./pages/components/Hero.tsx",
    "./pages/components/Create.tsx",
    "./pages/components/MarqueeContent.tsx",
    "./pages/components/MakeIt.tsx",
    "./pages/components/MonetizeIt.tsx",
    "./pages/components/ShareIt.tsx",
    "./pages/components/AnalyzeIt.tsx",
    "./pages/components/Community.tsx",
    "./pages/components/CommunityMarquee.tsx",
    "./pages/components/FAQ1.tsx",
    "./pages/components/FAQ2.tsx",
    "./pages/components/FAQ3.tsx",
    "./pages/components/FAQ4.tsx",
    "./pages/components/Question5.tsx",
    "./pages/components/Question6.tsx",
    "./pages/components/Question7.tsx",
    "./pages/components/Question8.tsx",
    "./pages/components/Question9.tsx",
    "./pages/components/Question10.tsx",
    "./pages/components/QuestionTitle.tsx",
    "./pages/components/GetStarted.tsx",
    "./pages/components/Footer.tsx",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
