import type { NextPage } from "next";
import Head from "next/head";
import Create from "./components/Create";

import Header from "./components/Header";
import Hero from "./components/Hero";
import MakeIt from "./components/MakeIt";
import MonetizeIt from "./components/MonetizeIt";
// import "~video-react/dist/video-react.css";

const Home: NextPage = () => {
  return (
    <div className="w-full h-full overflow-hidden">
      <Head>
        <title>Linkpop Shopify 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Hero />

      <Create />

      <MakeIt />

      <MonetizeIt />
    </div>
  );
};

export default Home;
