import type { NextPage } from "next";
import Head from "next/head";
import AnalyzeIt from "./components/AnalyzeIt";
import Community from "./components/Community";
import Create from "./components/Create";
import FAQ1 from "./components/FAQ1";
import FAQ2 from "./components/FAQ2";
import FAQ3 from "./components/FAQ3";
import FAQ4 from "./components/FAQ4";
import Header from "./components/Header";
import Hero from "./components/Hero";
import MakeIt from "./components/MakeIt";
import MonetizeIt from "./components/MonetizeIt";
import ShareIt from "./components/ShareIt";
// import "~video-react/dist/video-react.css";

const Home: NextPage = () => {
  return (
    <div className="w-full h-full overflow-hidden">
      <Head>
        <title>Linkpop Shopify 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Hero />

      <Create />

      <MakeIt />

      <MonetizeIt />

      <ShareIt />

      <AnalyzeIt />

      <Community />

      <FAQ1 />

      <FAQ2 />

      <FAQ3 />

      <FAQ4 />
    </div>
  );
};

export default Home;
